- name: make directory
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory

- name: Create ssh public key
  copy:
    owner: "{{ ansible_user }}"
    mode: '0600'
    dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    content: "{{ lookup('file', '{{ local_home_path | default('/home/'+privilege_user) }}/{{ ansible_user }}/.ssh/id_rsa.pub') }}"